#!/usr/bin/env bash

if [ $(readlink "$0") ]; then
  supportdir="$(dirname "$(dirname "$0")/$(readlink "$0")")/support"
else
  supportdir="$(dirname "$0")/support"
fi

if [ $1 == "sample" ]; then
  cat "$supportdir/model-example.cue"
  exit 0
fi

if [ -z $1 ]; then
  target=$(ls | grep 'repo\.\w\+' | head -n 1)
else
  target=$1
fi

echo "Vetting $target:"
cue vet "$supportdir/schema"/* "$target" -v -c
echo "Done"
