#!/usr/bin/env bash

schemadir="$(dirname "$0")"/schema

if [ -z $1 ]; then
  target=$(ls | grep 'repo\.\w\+' | head -n 1)
else
  target=$1
fi

echo "Vetting $target:"
cue vet "$schemadir"/* "$target" -v -c
echo "Done"
