name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ./repovet/build.sh
    - name: Package
      run: tar -cvzf repovet.tar.gz -C repovet/dist .
    - name: Upload Asset to Release
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./repovet.tar.gz
        asset_name: repovet-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
    - name: Bump Homebrew formula
      uses: mislav/bump-homebrew-formula-action@1
      if: (!github.event.release.prerelease)
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      with:
        formula-name: repovet
        homebrew-tap: nreilingh/homebrew-tap
        download-url: ${{ steps.upload_release_asset.outputs.browser_download_url }}
