# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: [ push, pull_request ]
  push:
    branches:
      - '**'
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Complete repovet build
        run: ./repovet/build.sh
      - name: Install CUE and ShellSpec
        run: brew install cuelang/tap/cue shellspec/shellspec/shellspec
      - name: Run test
        run: shellspec --format tap
