# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run test
        run: |
          wget "https://github.com/cuelang/cue/releases/download/v0.3.0-beta.8/cue_v0.3.0-beta.8_linux_arm64.tar.gz"
          echo "tar is" $(which tar)
          ls
          tar xzf cue_v0.3.0-beta.8_linux_arm64.tar.gz
          ls
          export PATH=$(pwd)/cue_v0.3.0-beta.8_linux_arm64:$PATH
          ./test.sh
